name: Run tests
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: "Setup Deno environment"
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.13.1
      - name: "Runs Test"
        run: |
          shopt -s globstar
          deno test --allow-all ./**/*test.ts
